# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'firestore_write_spike' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for firestore_write_spike
  pod 'Firebase/Core'

  target 'firestore_write_spikeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

